### PR TITLE
Remove smithy files from recipe directory [skip ci]

### LINKED ISSUE #6: Remove smithy files from recipe directory
https://github.com/conda-forge/httptools-feedstock/tree/master/recipe should contain a single meta.yml

### PR DESCRIPTION
**Pull request by kszucs**
fixes #6

### CODE REVIEW

**Review by xhochy — APPROVED** [review]

**Comment by kszucs** [comment]
Any ideas why the circleci builds are getting triggered despite skip ci message?

**Comment by xhochy** [comment]
Maybe this only works when `[skip ci]` is at the end?

**Comment by kszucs** [comment]
According to the [doc](https://circleci.com/docs/2.0/skip-build/) it should work, strange...

**Comment by carlodri** [comment]
Looks like there's something weird with conda smithy, better ask there

**Pull request merged**
